;/*FB_PKG_DELIM*/

__d("CometUnifiedShareSheetEmbedVideoContentQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="9702573803157362"}),null);
__d("CometUnifiedShareSheetEmbedVideoContentQuery$Parameters",["CometUnifiedShareSheetEmbedVideoContentQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometUnifiedShareSheetEmbedVideoContentQuery_facebookRelayOperation"),metadata:{},name:"CometUnifiedShareSheetEmbedVideoContentQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometEmbedVideoDialog.entrypoint",["CometUnifiedShareSheetEmbedVideoContentQuery$Parameters","JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.videoID;return{extraProps:{videoID:a},queries:{embedVideoQueryReference:{parameters:b("CometUnifiedShareSheetEmbedVideoContentQuery$Parameters"),variables:{videoID:a}}}}},root:c("JSResourceForInteraction")("CometEmbedVideoDialogRoot.react").__setRef("CometEmbedVideoDialog.entrypoint")};g["default"]=a}),98);
__d("FDSBookmarkCrossOutline20Icon",["cr:14545"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14545")}),98);
__d("FDSBookmarkCrossOutline20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("880859"),20);b=a;g["default"]=b}),98);
__d("FDSBookmarkOutline20Icon",["cr:14550"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14550")}),98);
__d("FDSBookmarkOutline20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("495628"),20);b=a;g["default"]=b}),98);
__d("FDSCodeOutline20Icon",["cr:14751"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14751")}),98);
__d("FDSCodeOutline20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("498857"),20);b=a;g["default"]=b}),98);
__d("ProfilePlusBoostEventsFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2791");b=d("FalcoLoggerInternal").create("profile_plus_boost_events",a);e=b;g["default"]=e}),98);
__d("SfvChainingNavigationScrollFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1465");b=d("FalcoLoggerInternal").create("sfv_chaining_navigation_scroll",a);e=b;g["default"]=e}),98);
__d("XCometCreatorCollaborationInviteControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/collaboration_invite/{video_id}/{secondary_collaborator_id}/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("XCometProfessionalDashboardCollaborationHomeControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/professional_dashboard/collaborations/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("groupGeminiPendingPostReminderDecrementUpdater",[],(function(a,b,c,d,e,f){"use strict";function a(a){var b=a.groupID;a=a.store;a=a.get(b);if(a==null)return;b=a.getLinkedRecords("work_group_reminder_list_renderer");if(b==null)return;var c=[];for(b of b){var d=!0;if(b!=null&&b.getValue("__typename")==="CometGroupPendingPostsReminderRenderer"){var e=b.getValue("count");if(typeof e==="number"){e=Math.max(e-1,0);e>0?b.setValue(e,"count"):d=!1}}d&&c.push(b)}a.setLinkedRecords(c,"work_group_reminder_list_renderer")}f["default"]=a}),66);
__d("groupsCometDeleteNodeFromConnection",["CometRelay","RelayFBConnectionHandler"],(function(a,b,c,d,e,f,g){"use strict";function a(a,b,c,e){b=a.get(b);if(b==null)return;((a=d("RelayFBConnectionHandler").getAllConnectionsWithKey(a,b,e))!=null?a:[]).forEach(function(a){return d("CometRelay").ConnectionHandler.deleteNode(a,c)})}g["default"]=a}),98);
__d("viewerContentUpdaterUtils",["CometRelay"],(function(a,b,c,d,e,f,g){"use strict";function a(a,b,c,e){a=a.get(b);if(a==null)return;var f;e==="PENDING"?f=d("CometRelay").ConnectionHandler.getConnection(c,"GroupsCometViewerContentPendingPostsFeed_stories",{content_type:e,ordering:"NEWEST_FIRST"}):e==="PUBLISHED"&&(f=d("CometRelay").ConnectionHandler.getConnection(c,"GroupsCometViewerContentPublishedPostsFeed_stories",{content_type:e,ordering:"NEWEST_FIRST"}));if(f==null)return;d("CometRelay").ConnectionHandler.insertEdgeBefore(f,a)}function b(a,b,c){b=b.getDataID();b=(b=a.get(b))==null?void 0:b.getLinkedRecord("stories",{content_type:c});if(b==null)return;c=b.getDataID();b=a.get(c);if(b==null)return;a=b.getValue("count_up_to",{max:51});typeof a==="number"&&b.setValue(Math.max(a-1,0),"count_up_to",{max:51});c=b.getValue("count_up_to",{max:1});typeof c==="number"&&typeof a==="number"&&a-1===0&&b.setValue(Math.max(c-1,0),"count_up_to",{max:1})}g.addEdgeToViewerContentConnection=a;g.decrementSectionCounts=b}),98);
__d("viewerContentPendingPostUpdater",["CometRelay","groupsCometDeleteNodeFromConnection","viewerContentUpdaterUtils"],(function(a,b,c,d,e,f,g){"use strict";function a(a){var b=a.groupID,e=a.store;a=a.storyID;if(b==null)return;b=e.get(b);if(b==null)return;b=b.getLinkedRecord("viewer_content");if(b==null)return;var f=b.getDataID();c("groupsCometDeleteNodeFromConnection")(e,f,a,"GroupsCometViewerContentPendingPostsFeed_stories");d("viewerContentUpdaterUtils").decrementSectionCounts(e,b,"PENDING")}function b(a,b){return function(c){if(b==null)return;c=c.get(a);if(c==null)return;c=c.getLinkedRecord("viewer_content");if(c==null)return;c=d("CometRelay").ConnectionHandler.getConnection(c,"GroupsCometViewerContentPendingPostsFeed_stories",{content_type:"PENDING",ordering:"NEWEST_FIRST"});if(c==null)return;d("CometRelay").ConnectionHandler.insertEdgeBefore(c,b)}}g.viewerContentDeletePendingPostUpdater=a;g.viewerContentAddPendingPostUpdater=b}),98);